Upgrade sidekiq-cron due to error with sidekiq v7
```
undefined method `options' for Sidekiq:Module
      new_version? ? Sidekiq[key] : Sidekiq.options[key]
                                           ^^^^^^^^
/var/www/petakopi/shared/bundle/ruby/3.1.0/gems/sidekiq-cron-1.8.0/lib/sidekiq/options.rb:6:in `[]'
/var/www/petakopi/shared/bundle/ruby/3.1.0/gems/sidekiq-cron-1.8.0/lib/sidekiq/cron/schedule_loader.rb:7:in `block in <main>'
/var/www/petakopi/shared/bundle/ruby/3.1.0/gems/sidekiq-7.1.6/lib/sidekiq.rb:98:in `configure_server'
/var/www/petakopi/shared/bundle/ruby/3.1.0/gems/sidekiq-cron-1.8.0/lib/sidekiq/cron/schedule_loader.rb:6:in `<main>
````